aws cloudformation list-stacks \
--stack-status-filter \
CREATE_IN_PROGRESS \
CREATE_FAILED \
CREATE_COMPLETE \
ROLLBACK_IN_PROGRESS \
ROLLBACK_FAILED \
ROLLBACK_COMPLETE \
DELETE_IN_PROGRESS \
DELETE_FAILED \
DELETE_COMPLETE 
